In [10]:
import numpy as np

In [11]:
a = [i for i in range(10)]

In [14]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
b = np.array(a)

In [16]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
type(b)

numpy.ndarray

In [21]:
b = np.array(a, dtype = float)

In [22]:
 b.ndim

1

In [23]:
b.shape

(10,)

# 2d array

In [25]:
b = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
b.ndim

2

In [28]:
b.shape

(3, 10)

In [29]:
b.size

30

In [30]:
b[1][1]

11

In [31]:
b[1][-1]

19

In [32]:
b[0, 9]

9

In [33]:
b[2, 5]

25

In [34]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [35]:
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [36]:
c = b[1:, 5:]

In [37]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [38]:
c[1, 4] = 999

In [39]:
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [40]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [41]:
b[1, 5] = 55

In [42]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  55,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [43]:
c

array([[ 55,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [44]:
c = b[1:, 5:].copy()

In [45]:
c[0, 0] = 777

In [46]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  55,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [47]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [48]:
b[1, 5] = 888

In [49]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 888,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [50]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

# простейщие действия с матрицами

In [51]:
import numpy as np

In [52]:
a = np.array([0, 1, 2, 3, 4])

In [53]:
b = np.array([5, 6, 7, 8, 9])

### сложение векторов

In [54]:
c = a + b

In [55]:
c

array([ 5,  7,  9, 11, 13])

In [56]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]
x3 = x1 + x2
x3

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

### вычитание векторов

In [58]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [59]:
 d = a - b

In [60]:
d

array([ 2, -1,  1,  3,  0])

In [61]:
d = np.subtract(a, b)

In [62]:
d

array([ 2, -1,  1,  3,  0])

In [63]:
a.shape == b.shape

True

### умножение вектора на скаляр

In [64]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [65]:
c = a * 2

In [66]:
c

array([10,  8, 16,  8,  6])

In [67]:
c = a * -10
c

array([-50, -40, -80, -40, -30])

In [68]:
c = a * 0.5
c

array([2.5, 2. , 4. , 2. , 1.5])

### альтернативные варианты умножения вектора на скаляр

In [69]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [70]:
# Вариант 1
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [71]:
# Вариант 2
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [72]:
# Вариант 3
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

### скалярное произведение векторов

In [73]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [74]:
a.shape

(3,)

In [75]:
b.shape

(3,)

In [76]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

32

In [77]:
a @ b

32

In [80]:
sp = np.dot(a, b)
sp

32

### операции над матрицами

In [82]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

In [83]:
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [84]:
A.shape

(3, 2)

In [85]:
B.shape

(3, 2)

### сложение матриц

In [86]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

Альтернативный способ

In [87]:
C = np.add(A, B)

In [88]:
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

### Вычитание матриц

In [89]:
C = A - B
C

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [91]:
np.subtract(A, B)

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

### Умножение матрицы на скаляр

In [92]:
x = np.array([[1, 2],[3, 4]])
x

array([[1, 2],
       [3, 4]])

In [93]:
y = x * 3
y

array([[ 3,  6],
       [ 9, 12]])

In [94]:
y = np.dot(x, 3)

In [95]:
y

array([[ 3,  6],
       [ 9, 12]])

# Умножение матриц друг на друга

In [96]:
x1 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

In [97]:
x2 = np.array([[7, 8, 9, 10],
               [11, 12, 13, 14]])

In [100]:
x1.shape[1] == x2.shape[0]

True

In [101]:
x1.shape, x2.shape

((3, 2), (2, 4))

In [102]:
z = np.dot(x1, x2)
z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [103]:
z.shape

(3, 4)

In [104]:
 z[0, 0]

29

In [105]:
x1[0, 0] * x2[0, 0] + x1[0, 1] * x2[1, 0]

29

### модуль numpy.linalg : возведение матрицы в квадрат

In [106]:
A = np.array([[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]])

In [107]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [108]:
A_square = np.dot(A, A)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [109]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

### создание единичной матрицы

In [110]:
# Единичная матрица - квадратная матрица с единицами на главной диагонали и нулями в остальных ячейках
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ### Умножение матрицы на единичную матрицу

In [111]:
x1 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

In [112]:
x2 = np.eye(2)

In [113]:
y = np.dot(x1, x2)

In [114]:
y

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [116]:
x2 = np.eye(3)

In [117]:
y = np.dot(x2, x1)
y

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### Транспонирование матрицы

In [119]:
A = np.array([[11, 13],
               [16, 9],
               [8, 15]])

In [120]:
At = np.transpose(A)

In [121]:
At

array([[11, 16,  8],
       [13,  9, 15]])

альтернативный вариант

In [122]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

### Вычисление определителя и ранга матрицы

In [127]:
B = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

In [129]:
np.linalg.det(B)

0.0

In [130]:
np.linalg.matrix_rank(B)

2

In [131]:
C = np.array([[7, 4, 5],
                [8, 3, 2],
                [6, 10, 12]])

In [132]:
np.linalg.det(C)

85.99999999999997

In [133]:
np.linalg.matrix_rank(C)

3

In [134]:
D = np.array([[1, 2],
                [3, 4],
                [5, 6]])

In [135]:
np.linalg.matrix_rank(D)

2

### вычисление обратной матрицы

In [136]:
 B = np.array([[7, 4, 5],
                [8, 3, 2],
                [6, 10, 12]])

In [137]:
B_inv = np.linalg.inv(B)

In [138]:
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [139]:
B_inv2 = np.linalg.inv(B_inv)

In [140]:
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

# Автоматическое создание массивов

In [145]:
A = np.zeros((3, 4))

In [146]:
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [147]:
B = np.ones((5, 4))
B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [148]:
 np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [151]:
 np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [152]:
 np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

In [153]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

# numpy.linspace - тоже самое что и arange, но нужно учитывать что правая 
# граница будет включена и вместо шага указывается нужное число элементов


In [154]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### numpy.logspace - похожа на linspace, но вместо границ указываются степени числа 10

In [155]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

### генерация случайных чисел

### numpy.random.sample - случайные числа с равномерным распределением от [0.0 до 1.0)

In [157]:
np.random.sample()

0.1782213028255092

In [159]:
# одномерный массив 3-х элементов
np.random.sample(3)

array([0.847576  , 0.6372385 , 0.36077762])

In [161]:
# двумерный массив 2 на 3
np.random.sample((2, 3))

array([[0.85281705, 0.63831228, 0.8027922 ],
       [0.75362578, 0.23395595, 0.10909789]])

### numpy.random.randn - случайные числа с нормальным распределением 
(среднее значение 0, среднеквадратичное отклоение - 0)

In [162]:
np.random.randn(10)

array([ 1.03153635, -0.30666016,  2.19978747,  0.72423678, -0.71404541,
       -0.56471495,  0.60929198,  1.26464111, -0.26779982,  1.99115613])

In [163]:
np.random.randn(3, 4)

array([[-1.24655316,  0.49810964,  0.66964339,  0.31838979],
       [-0.92085275, -1.09115623,  0.25430604,  0.53922237],
       [ 0.5456098 , -0.11518633,  2.79355178, -0.96253523]])

### numpy.random.randint - массив из целых случайных чисел
(среднее значение 0, среднеквадратичное отклоение - 0)

In [164]:
np.random.randint(1, 100, 10)

array([67, 45, 90, 84, 67, 22,  7, 72, 61, 52])

In [166]:
np.random.randint(0, 10, (3, 4))

array([[4, 0, 7, 4],
       [1, 8, 2, 4],
       [4, 7, 9, 1]])

### numpy.random.choice - случайный выбор элементов из массива


In [167]:
a = np.array([5, 4, 8, 4, 3])

In [169]:
np.random.choice(a)

5

In [171]:
np.random.choice(a, 3)

array([8, 5, 4])

### numpy.random.seed - инициализация генератора случайных чисел

In [172]:
np.random.seed(30)

In [173]:
np.random.randint(0, 10, 3)

array([5, 5, 4])

In [174]:
np.random.randint(0, 10, 3)

array([7, 2, 5])

In [175]:
np.random.randint(0, 10, 3)

array([1, 3, 9])

In [176]:
np.random.seed(30)

In [177]:
np.random.randint(0, 10, 3)

array([5, 5, 4])

In [178]:
np.random.seed(30)

In [179]:
np.random.randint(0, 10, 3)

array([5, 5, 4])

### изменение формы массива

In [180]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [181]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [182]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [183]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [185]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [186]:
a.resize(3, 4)

In [187]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
a = a.flatten()

In [190]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### соединение массивов

In [191]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [192]:
b = np.ones((2, 3))

In [193]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

соединение строк вертикально

In [195]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [196]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [197]:
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

соединение столбцов горизонтально

In [198]:
h = np.hstack((a, b))

In [199]:
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [201]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [202]:
np.concatenate((a, b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

соединение в глубину двух массивов

In [203]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

# Функции для работы с данными

### выбор данных

In [204]:
a = np.random.randint(0, 20, 10)

In [205]:
a

array([12,  2, 17, 14,  3,  9,  7,  1, 17, 13])

In [206]:
a[a > 10]

array([12, 17, 14, 17, 13])

In [207]:
a[(a > 10) & (a % 2 == 0)]

array([12, 14])

In [208]:
a[(a > 10) | (a % 3 == 0)]

array([12, 17, 14,  3,  9, 17, 13])

numpy - первый вариант применения (возвращает индексы чисел, которые удовлетворяют условию или возвращает сами числа по условию)

In [210]:
a

array([12,  2, 17, 14,  3,  9,  7,  1, 17, 13])

In [211]:
np.where(a > 10)

(array([0, 2, 3, 8, 9]),)

In [212]:
a[np.where(a > 10)]

array([12, 17, 14, 17, 13])

In [213]:
a = [1, 4, 7]
b = [3, 5, 9]

In [214]:
np.where([True, False, True], a, b)

array([1, 5, 7])

### сортировка данных

In [215]:
a = np.array([[1, 3, 9, 9],
             [5, 0, 1, 5],
            [2, 7, 3, 5]])
a

array([[1, 3, 9, 9],
       [5, 0, 1, 5],
       [2, 7, 3, 5]])

In [216]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [219]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]])

In [222]:
a[:, 0].argsort()

array([0, 2, 1])

In [223]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [224]:
a[a[:, 1].argsort(), :]

array([[5, 0, 1, 5],
       [1, 3, 9, 9],
       [2, 7, 3, 5]])

In [226]:
a[:, a[:, 1].argsort()]

array([[3, 1, 9],
       [0, 5, 1],
       [7, 2, 3]])

In [227]:
a[:, a[:, 0].argsort()]

array([[1, 9, 3],
       [5, 1, 0],
       [2, 3, 7]])

In [228]:
a[0, a[:, 0].argsort()]

array([1, 9, 3])

In [230]:
a[0, :].argsort()

array([0, 1, 2, 3])

In [232]:
a[:, a[0, :].argsort()]

array([[1, 3, 9, 9],
       [5, 0, 1, 5],
       [2, 7, 3, 5]])

In [233]:
a[:, a[1, :].argsort()]

array([[3, 9, 1, 9],
       [0, 1, 5, 5],
       [7, 3, 2, 5]])

### случайное перемешивание массивов

одномерные массивы

In [234]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [235]:
# перемешивание на месте - in place
np.random.shuffle(a)
a

array([1, 9, 7, 0, 5, 6, 4, 8, 2, 3])

двумерные массивы

In [238]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [239]:
# перемешивание на месте - in place (перемешиваться будут только строки)
np.random.shuffle(a)
a

array([[ 9, 10, 11],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2]])

# математические действия с массивами

### применение математических функций ко всему массиву

In [241]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [242]:
# логарифм по основанию е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [243]:
# экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [244]:
# сумма всех элементов матрицы
np.sum(a)

21

In [245]:
 # сумма всех элементов матрицы
a.sum()

21

In [247]:
# просуммируются значения по каждому столбцу 
a.sum(axis = 0)

array([5, 7, 9])

In [248]:
# просуммируются значения по каждой строке 
a.sum(axis = 1)

array([ 6, 15])

In [249]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [250]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

 поэлементное (не матричное) умное двух массивов

In [251]:
a = np.arange(12).reshape(3, 4)

In [252]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [253]:
b = np.arange(12, 24).reshape(3, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [254]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Broadcasting (на примере сложения)

In [255]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])
a

array([[2, 5],
       [3, 4],
       [6, 1]])

1 случай - совпадает только кол-во столбцов (при сложении к каждой строке первой матрицы прибавится строка второй)

In [256]:
b = np.array([1, 2])
b

array([1, 2])

In [257]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

2 случай - совпадает только кол-во строк (при сложении к каждому столбцу первой матрицы прибавится столбец второй)

In [258]:
a

array([[2, 5],
       [3, 4],
       [6, 1]])

In [259]:
b = np.array([[1], 
            [2], 
            [3]])
b

array([[1],
       [2],
       [3]])

In [260]:
a + b

array([[3, 6],
       [5, 6],
       [9, 4]])

### статистические функции

In [261]:
a = np.random.randint(0, 12, (3, 4))

In [262]:
a

array([[ 7,  4,  2,  1],
       [ 7,  1, 10, 11],
       [ 9,  8, 11,  5]])

In [263]:
a.min()

1

In [264]:
a.max()

11

In [265]:
# минимальное значение для каждого столбца
a.min(axis = 0)

array([7, 1, 2, 1])

In [266]:
# максимальное значение для каждой строки
a.max(axis = 1)

array([ 7, 11, 11])

In [267]:
# среднее значение для каждой столбца
a.mean(axis = 0)

array([7.66666667, 4.33333333, 7.66666667, 5.66666667])

In [268]:
# средне квадратичное отклонение значение для каждой столбца
a.std(axis = 0)

array([0.94280904, 2.86744176, 4.02768199, 4.10960934])

### запись и чтение массива из файла

In [269]:
a

array([[ 7,  4,  2,  1],
       [ 7,  1, 10, 11],
       [ 9,  8, 11,  5]])

In [270]:
# сохраняем массив а в файл
np.save('a.npy', a)

In [271]:
# выгружаем из файла массив
b = np.load('a.npy')

In [272]:
b

array([[ 7,  4,  2,  1],
       [ 7,  1, 10, 11],
       [ 9,  8, 11,  5]])

# Библиотека Pandas

In [273]:
import pandas as pd

### создание Series (одна из структур данных в Pandas, похожа на словарь, но упорядочена)

In [274]:
a = [2, 5, 7, 8, 3]

In [275]:
b = pd.Series(a)

In [276]:
b

0    2
1    5
2    7
3    8
4    3
dtype: int64

In [277]:
b = pd.Series(a, index = [0, 1, 2, 3, 4])

In [278]:
b

0    2
1    5
2    7
3    8
4    3
dtype: int64

In [279]:
b = pd.Series(a, index = ['a', 'b', 'c', 'd', 'e'])

In [280]:
b

a    2
b    5
c    7
d    8
e    3
dtype: int64

также можно использовать вместо индексов даты

In [281]:
from datetime import date 

In [282]:
ind = [date(y, m, d) for y, m, d in [(2018, 1, 15), (2018, 1, 17), (2018, 1, 18), (2018, 1, 21), (2018, 1, 31)]]

In [283]:
b = pd.Series(a, index = ind)
b

2018-01-15    2
2018-01-17    5
2018-01-18    7
2018-01-21    8
2018-01-31    3
dtype: int64

In [285]:
b.index

Index([2018-01-15, 2018-01-17, 2018-01-18, 2018-01-21, 2018-01-31], dtype='object')

In [286]:
b.index[0].year

2018

In [287]:
b.index[0].month

1

In [288]:
b.index[0].day

15

In [290]:
b.index = pd.to_datetime(b.index, format = '%Y-%m-%d')

In [291]:
b.index

DatetimeIndex(['2018-01-15', '2018-01-17', '2018-01-18', '2018-01-21',
               '2018-01-31'],
              dtype='datetime64[ns]', freq=None)

In [292]:
b.index[0]

Timestamp('2018-01-15 00:00:00')

In [293]:
b.index.year

Int64Index([2018, 2018, 2018, 2018, 2018], dtype='int64')

In [294]:
b.index.month

Int64Index([1, 1, 1, 1, 1], dtype='int64')

In [295]:
b.index.day

Int64Index([15, 17, 18, 21, 31], dtype='int64')

индекся могут быть неуникальными и могут повторяться

In [296]:
b = pd.Series(a, index = [0, 1, 0, 1, 4])

In [297]:
b.index

Int64Index([0, 1, 0, 1, 4], dtype='int64')

In [298]:
b

0    2
1    5
0    7
1    8
4    3
dtype: int64

In [299]:
b.index = [0, 1, 2, 3, 4]
b

0    2
1    5
2    7
3    8
4    3
dtype: int64

задать тип данных

In [300]:
b = pd.Series(a, dtype = np.float64)

In [301]:
b

0    2.0
1    5.0
2    7.0
3    8.0
4    3.0
dtype: float64

можно поменять тип данных:

In [302]:
b = pd.Series(a)
b = b.astype(np.float64)

In [303]:
b

0    2.0
1    5.0
2    7.0
3    8.0
4    3.0
dtype: float64

создать Series из словаря

In [304]:
d = {'1st':'a', '2nd':'b', '3rd':'c', '4th':'d', '5th':'e'}

In [305]:
b = pd.Series(d)

In [306]:
b

1st    a
2nd    b
3rd    c
4th    d
5th    e
dtype: object

### просмотр данных

In [307]:
b = pd.Series([5, 2, 6, 1, 6, 8, 7])

In [308]:
b.index

RangeIndex(start=0, stop=7, step=1)

просмотреть данные в виде массива numpy(ndarray)

In [309]:
b.values

array([5, 2, 6, 1, 6, 8, 7])

In [310]:
b

0    5
1    2
2    6
3    1
4    6
5    8
6    7
dtype: int64

In [311]:
b[0]

5

In [312]:
b[5]

8

доступ по списку индексов

In [313]:
b[[0, 6]]

0    5
6    7
dtype: int64

доступ с помощью head, tail

In [315]:
b.head()

0    5
1    2
2    6
3    1
4    6
dtype: int64

In [316]:
b.head(6)

0    5
1    2
2    6
3    1
4    6
5    8
dtype: int64

In [318]:
b.tail()

2    6
3    1
4    6
5    8
6    7
dtype: int64

In [319]:
b.tail(1)

6    7
dtype: int64

In [320]:
b[b > 5]

2    6
4    6
5    8
6    7
dtype: int64

### изменение элементов Series

In [321]:
b = pd.Series([5, 2, 6, 1, 6, 8, 7])
b

0    5
1    2
2    6
3    1
4    6
5    8
6    7
dtype: int64

In [322]:
b[4]

6

In [323]:
b[0]

5

In [324]:
b[0] = 4

In [325]:
b

0    4
1    2
2    6
3    1
4    6
5    8
6    7
dtype: int64

In [326]:
b[b < 5] = 0

In [327]:
b

0    0
1    0
2    6
3    0
4    6
5    8
6    7
dtype: int64

In [328]:
b[[0, 1, 2]] = 1

In [329]:
b

0    1
1    1
2    1
3    0
4    6
5    8
6    7
dtype: int64

### добавление данных в Series

In [330]:
b

0    1
1    1
2    1
3    0
4    6
5    8
6    7
dtype: int64

In [331]:
b = b.append(pd.Series({6:12, 7:45, 8:123, 9:32}))
b

0      1
1      1
2      1
3      0
4      6
5      8
6      7
6     12
7     45
8    123
9     32
dtype: int64

### удаление данных из Series

In [332]:
b

0      1
1      1
2      1
3      0
4      6
5      8
6      7
6     12
7     45
8    123
9     32
dtype: int64

In [333]:
b = b.drop([0, 1, 2])
b

3      0
4      6
5      8
6      7
6     12
7     45
8    123
9     32
dtype: int64

 ### запись и чтение данных Series из файла

In [334]:
# запись в файл
b.to_pickle('b.pkl')

In [335]:
# чтение из файла
b2 = pd.read_pickle('b.pkl')
b2

3      0
4      6
5      8
6      7
6     12
7     45
8    123
9     32
dtype: int64

### DataFrame - двумерная структура данных библиотеки Pandas

Создание DataFrame

In [336]:
df = pd.DataFrame({'Col1':['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], 'Col2':[1, 3, 5, 7, 9, 11, 13, 15]}, columns= ['Col1', 'Col2'])

In [337]:
df

Col1  Col2
0    a     1
1    b     3
2    c     5
3    d     7
4    e     9
5    f    11
6    g    13
7    h    15

просмотр информации о DataFrame

In [338]:
df.shape

(8, 2)

In [342]:
df.columns

Index(['Col1', 'Col2'], dtype='object')

In [343]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [345]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Col1    8 non-null      object
 1   Col2    8 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 256.0+ bytes


In [346]:
df.describe()

Col2
count   8.000000
mean    8.000000
std     4.898979
min     1.000000
25%     4.500000
50%     8.000000
75%    11.500000
max    15.000000

In [347]:
df.head()

Col1  Col2
0    a     1
1    b     3
2    c     5
3    d     7
4    e     9

In [348]:
df.head(2)

Col1  Col2
0    a     1
1    b     3

In [349]:
 df['Col1'].head(2)

0    a
1    b
Name: Col1, dtype: object

In [350]:
 df.Col1.head(2)

0    a
1    b
Name: Col1, dtype: object

In [351]:
df.tail()

Col1  Col2
3    d     7
4    e     9
5    f    11
6    g    13
7    h    15

### Изменение индекса DataFrame

In [352]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [353]:
df.index = [2, 4, 6, 8, 10, 12, 14, 16]

In [354]:
df

Col1  Col2
2     a     1
4     b     3
6     c     5
8     d     7
10    e     9
12    f    11
14    g    13
16    h    15

 ВЫбор данных по индексу:

In [355]:
df.loc[2, 'Col1']

'a'

In [356]:
df.loc[2, :]

Col1    a
Col2    1
Name: 2, dtype: object

In [357]:
df.loc[2:4, :]

Col1  Col2
2    a     1
4    b     3

Выбор данных по позиции:

In [358]:
df

Col1  Col2
2     a     1
4     b     3
6     c     5
8     d     7
10    e     9
12    f    11
14    g    13
16    h    15

In [359]:
df.iloc[0, :]

Col1    a
Col2    1
Name: 2, dtype: object

In [360]:
df.iloc[0:2, :]

Col1  Col2
2    a     1
4    b     3

In [361]:
df.iloc[0:2, 0]

2    a
4    b
Name: Col1, dtype: object

Выбор данных по условию

In [365]:
df.loc[df['Col1'] == 'b', :]

Col1  Col2
4    b     3

In [364]:
df.loc[df['Col1'] == 'b', 'Col2']

4    3
Name: Col2, dtype: int64

In [366]:
df.loc[df['Col1'] == 'b', 'Col2'].values

array([3])

In [367]:
df.loc[df['Col2'] > 10, 'Col1']

12    f
14    g
16    h
Name: Col1, dtype: object

In [368]:
df.loc[(df['Col2'] > 10) | (df['Col2'] % 9 == 0), :]

Col1  Col2
10    e     9
12    f    11
14    g    13
16    h    15

In [370]:
df.loc[(df['Col2'] > 10) & (df['Col1'] != 'g'), :]

Col1  Col2
12    f    11
16    h    15

In [371]:
df.loc[df['Col2'].between(11, 13), :]

Col1  Col2
12    f    11
14    g    13

In [373]:
df.loc[df['Col1'].isin(['a', 'b', 'c', 'd']), :]

Col1  Col2
2    a     1
4    b     3
6    c     5
8    d     7

In [374]:
df.loc[~df['Col1'].isin(['a', 'b', 'c', 'd']), :]

Col1  Col2
10    e     9
12    f    11
14    g    13
16    h    15

### Метод query

In [375]:
df

Col1  Col2
2     a     1
4     b     3
6     c     5
8     d     7
10    e     9
12    f    11
14    g    13
16    h    15

In [378]:
df.query('Col1 == "b"')

Col1  Col2
4    b     3

In [380]:
df.query('Col2 > 10')

Col1  Col2
12    f    11
14    g    13
16    h    15

столбец DataFrame в виде Series

In [381]:
s = df['Col1']
s

2     a
4     b
6     c
8     d
10    e
12    f
14    g
16    h
Name: Col1, dtype: object

In [382]:
type(s)

pandas.core.series.Series

получение DataFrame из Series

In [383]:
df2 = pd.DataFrame(s)

In [384]:
df2

Col1
2     a
4     b
6     c
8     d
10    e
12    f
14    g
16    h

In [385]:
type(df2)

pandas.core.frame.DataFrame

### копирование DataFrame

In [386]:
df_copy = df.copy()

In [387]:
df_copy

Col1  Col2
2     a     1
4     b     3
6     c     5
8     d     7
10    e     9
12    f    11
14    g    13
16    h    15

### случайный выбор n-ого кол-ва строк из DataFrame

In [388]:
df.sample(n = 2)

Col1  Col2
10    e     9
6     c     5

In [390]:
df

Col1  Col2
2     a     1
4     b     3
6     c     5
8     d     7
10    e     9
12    f    11
14    g    13
16    h    15

### Случайный выбор доли из исходного DataFrame

In [391]:
df.sample(frac = 0.5)

Col1  Col2
6     c     5
14    g    13
12    f    11
2     a     1

### Случайный выбор с возвращением (строки. могут повторяться)

In [392]:
df.sample(frac = 0.5, replace = True)

Col1  Col2
8     d     7
16    h    15
8     d     7
10    e     9

### Случайное перемешивание

In [393]:
# random_state - для воспроизводимости перемешивания
df.sample(frac = 1, random_state=42)

Col1  Col2
4     b     3
12    f    11
2     a     1
16    h    15
6     c     5
10    e     9
8     d     7
14    g    13

### Запись и чтения DataFrame в файл формата .csv

In [394]:
# запись в файл с разделителем ; (по умолчанию - ","), и без записи индексов
df.to_csv('test.csv', sep = ';', index = False)

In [395]:
df_new = pd.read_csv('test.csv', sep = ';')

In [396]:
df_new

Col1  Col2
0    a     1
1    b     3
2    c     5
3    d     7
4    e     9
5    f    11
6    g    13
7    h    15

In [397]:
# Запись в эксель или пикл также возможна: to_excel, to_pickle. read_excel, read_pickle 

### Слияние данных в DataFrame

In [398]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 'author_name':['Pushkin', 'Tolstoy', 'Dostoevskiy']}, columns = ['author_id', 'author_name'])

In [399]:
authors

author_id  author_name
0          1      Pushkin
1          2      Tolstoy
2          3  Dostoevskiy

In [400]:
books = pd.DataFrame({'author_id':[2, 3, 3, 4], 'book_title':['War and Peace', 'The Idiot', 'Crime and Punishment', 'Fathers and Sons']}, columns = ['author_id', 'book_title'])

In [401]:
books

author_id            book_title
0          2         War and Peace
1          3             The Idiot
2          3  Crime and Punishment
3          4      Fathers and Sons

Merge

In [403]:
df1 = pd.merge(authors, books, on = 'author_id', how = 'inner')
df1

author_id  author_name            book_title
0          2      Tolstoy         War and Peace
1          3  Dostoevskiy             The Idiot
2          3  Dostoevskiy  Crime and Punishment

Left merge

In [404]:
df2 = pd.merge(authors, books, on = 'author_id', how = 'left')
df2

author_id  author_name            book_title
0          1      Pushkin                   NaN
1          2      Tolstoy         War and Peace
2          3  Dostoevskiy             The Idiot
3          3  Dostoevskiy  Crime and Punishment

Right merge

In [405]:
df3 = pd.merge(authors, books, on = 'author_id', how = 'right')
df3

author_id  author_name            book_title
0          2      Tolstoy         War and Peace
1          3  Dostoevskiy             The Idiot
2          3  Dostoevskiy  Crime and Punishment
3          4          NaN      Fathers and Sons

Outer merge

In [406]:
df4 = pd.merge(authors, books, on = 'author_id', how = 'outer')
df4

author_id  author_name            book_title
0          1      Pushkin                   NaN
1          2      Tolstoy         War and Peace
2          3  Dostoevskiy             The Idiot
3          3  Dostoevskiy  Crime and Punishment
4          4          NaN      Fathers and Sons

### Работа с пропущенными данными в DataFrame

In [407]:
df4.loc[df4['book_title'].isnull(), :]

author_id author_name book_title
0          1     Pushkin        NaN

In [408]:
df4.loc[df4['book_title'].notnull(), :]

author_id  author_name            book_title
1          2      Tolstoy         War and Peace
2          3  Dostoevskiy             The Idiot
3          3  Dostoevskiy  Crime and Punishment
4          4          NaN      Fathers and Sons

In [409]:
df4.loc[df4['author_name'].notnull(), :]

author_id  author_name            book_title
0          1      Pushkin                   NaN
1          2      Tolstoy         War and Peace
2          3  Dostoevskiy             The Idiot
3          3  Dostoevskiy  Crime and Punishment

In [412]:
df4['book_title'] = df4['book_title'].fillna('unknown')

In [413]:
df4['book_title']

0                 unknown
1           War and Peace
2               The Idiot
3    Crime and Punishment
4        Fathers and Sons
Name: book_title, dtype: object

In [414]:
df4['author_name'].fillna('unknown', inplace=True)

In [415]:
df4

author_id  author_name            book_title
0          1      Pushkin               unknown
1          2      Tolstoy         War and Peace
2          3  Dostoevskiy             The Idiot
3          3  Dostoevskiy  Crime and Punishment
4          4      unknown      Fathers and Sons

### Добавление столбцов в DataFrame

In [416]:
df4.loc[(df4['author_name'] != 'unknown') & (df4['book_title'] != 'unknown'), 'quantity'] = 1 

In [417]:
df4

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown       NaN
1          2      Tolstoy         War and Peace       1.0
2          3  Dostoevskiy             The Idiot       1.0
3          3  Dostoevskiy  Crime and Punishment       1.0
4          4      unknown      Fathers and Sons       NaN

In [418]:
df4['quantity'].fillna(0, inplace=True)

In [419]:
df4

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown       0.0
1          2      Tolstoy         War and Peace       1.0
2          3  Dostoevskiy             The Idiot       1.0
3          3  Dostoevskiy  Crime and Punishment       1.0
4          4      unknown      Fathers and Sons       0.0

In [421]:
df4['quantity'] = df4['quantity'].astype(int)
df4

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown         0
1          2      Tolstoy         War and Peace         1
2          3  Dostoevskiy             The Idiot         1
3          3  Dostoevskiy  Crime and Punishment         1
4          4      unknown      Fathers and Sons         0

In [422]:
type(df4['quantity'])

pandas.core.series.Series

In [423]:
df4['quantity']

0    0
1    1
2    1
3    1
4    0
Name: quantity, dtype: int64

In [425]:
df4.set_index('author_id', inplace=True)
df4

author_name            book_title  quantity
author_id                                             
1              Pushkin               unknown         0
2              Tolstoy         War and Peace         1
3          Dostoevskiy             The Idiot         1
3          Dostoevskiy  Crime and Punishment         1
4              unknown      Fathers and Sons         0

In [426]:
df4.reset_index(inplace=True)
df4

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown         0
1          2      Tolstoy         War and Peace         1
2          3  Dostoevskiy             The Idiot         1
3          3  Dostoevskiy  Crime and Punishment         1
4          4      unknown      Fathers and Sons         0

### удаление данных в DataFrame

In [427]:
df4['price'] = 500

In [428]:
df4

author_id  author_name            book_title  quantity  price
0          1      Pushkin               unknown         0    500
1          2      Tolstoy         War and Peace         1    500
2          3  Dostoevskiy             The Idiot         1    500
3          3  Dostoevskiy  Crime and Punishment         1    500
4          4      unknown      Fathers and Sons         0    500

In [429]:
type(df4)

pandas.core.frame.DataFrame

Удалим столбец:

In [430]:
df4 = df4.drop('price', axis = 1)
df4

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown         0
1          2      Tolstoy         War and Peace         1
2          3  Dostoevskiy             The Idiot         1
3          3  Dostoevskiy  Crime and Punishment         1
4          4      unknown      Fathers and Sons         0

Удалим строку по значению индекс:

In [431]:
df4 = df4.drop(1, axis = 0)
df4

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown         0
2          3  Dostoevskiy             The Idiot         1
3          3  Dostoevskiy  Crime and Punishment         1
4          4      unknown      Fathers and Sons         0

### сортировка данных в DataFrame

In [432]:
df4 = df4.append(pd.DataFrame({'author_id': [2], 'author_name': ['Tolstoy'], 'book_title': ['War and Peace'],
                               'quantity': [1]}, columns=['author_id', 'author_name', 
                                                          'book_title', 'quantity']), 
                 ignore_index=True)
df4

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown         0
1          3  Dostoevskiy             The Idiot         1
2          3  Dostoevskiy  Crime and Punishment         1
3          4      unknown      Fathers and Sons         0
4          2      Tolstoy         War and Peace         1

Отсортируем DataFrame по столбцу author_id

In [433]:
df4 = df4.sort_values(by='author_id')
df4

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown         0
4          2      Tolstoy         War and Peace         1
1          3  Dostoevskiy             The Idiot         1
2          3  Dostoevskiy  Crime and Punishment         1
3          4      unknown      Fathers and Sons         0

In [434]:
df4.reset_index(drop=True)

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown         0
1          2      Tolstoy         War and Peace         1
2          3  Dostoevskiy             The Idiot         1
3          3  Dostoevskiy  Crime and Punishment         1
4          4      unknown      Fathers and Sons         0

### Соединение (конкатенация) DataFrame

In [435]:
df5 = pd.DataFrame({'author_id': [3, 5], 'author_name': ['Dostoevskiy', 'Chekhov'], 'book_title': ['The Gambler', 
                                        'Three sisters'], 'quantity': [2, 3]}, columns=['author_id', 'author_name', 
                                                          'book_title', 'quantity'])
df5

author_id  author_name     book_title  quantity
0          3  Dostoevskiy    The Gambler         2
1          5      Chekhov  Three sisters         3

In [436]:
df6 = pd.concat([df4, df5], axis = 0, ignore_index=True)

In [437]:
df6

author_id  author_name            book_title  quantity
0          1      Pushkin               unknown         0
1          2      Tolstoy         War and Peace         1
2          3  Dostoevskiy             The Idiot         1
3          3  Dostoevskiy  Crime and Punishment         1
4          4      unknown      Fathers and Sons         0
5          3  Dostoevskiy           The Gambler         2
6          5      Chekhov         Three sisters         3

Конкатенация по оси 1(добавдение новых столбцов / соединение по столбцам)

In [438]:
prices = pd.DataFrame({'price':[700, 450, 500, 400, 350]}, columns=['price'], index = [1, 2, 3, 5, 6])
prices

price
1    700
2    450
3    500
5    400
6    350

In [439]:
df7 = pd.concat([df6, prices], axis = 1)
df7

author_id  author_name            book_title  quantity  price
0          1      Pushkin               unknown         0    NaN
1          2      Tolstoy         War and Peace         1  700.0
2          3  Dostoevskiy             The Idiot         1  450.0
3          3  Dostoevskiy  Crime and Punishment         1  500.0
4          4      unknown      Fathers and Sons         0    NaN
5          3  Dostoevskiy           The Gambler         2  400.0
6          5      Chekhov         Three sisters         3  350.0

### Применение функций и методов в DataFrame

In [440]:
df7['total'] = df7['quantity'] * df7['price']
df7

author_id  author_name            book_title  quantity  price   total
0          1      Pushkin               unknown         0    NaN     NaN
1          2      Tolstoy         War and Peace         1  700.0   700.0
2          3  Dostoevskiy             The Idiot         1  450.0   450.0
3          3  Dostoevskiy  Crime and Punishment         1  500.0   500.0
4          4      unknown      Fathers and Sons         0    NaN     NaN
5          3  Dostoevskiy           The Gambler         2  400.0   800.0
6          5      Chekhov         Three sisters         3  350.0  1050.0

In [442]:
df7['price'].min()

350.0

In [443]:
df7['price'].max()

700.0

In [444]:
df7['price'].mean()

480.0

In [445]:
df7['price'].median()

450.0

In [446]:
# среднеквадратичное отклонение
df7['price'].std()

135.09256086106296

In [447]:
# дисперсия
df7['price'].var()

18250.0

In [448]:
# вывод нескольких максимальных значений
df7.nlargest(3, 'price')

author_id  author_name            book_title  quantity  price  total
1          2      Tolstoy         War and Peace         1  700.0  700.0
3          3  Dostoevskiy  Crime and Punishment         1  500.0  500.0
2          3  Dostoevskiy             The Idiot         1  450.0  450.0

In [449]:
# вывод уникального значения столбца 
df7['author_name'].unique()

array(['Pushkin', 'Tolstoy', 'Dostoevskiy', 'unknown', 'Chekhov'],
      dtype=object)

In [450]:
# количество уникальных значений в столбце
df7['author_name'].nunique()

5

In [451]:
# количество повторений каждого значения в столбце
df7['author_name'].value_counts()

Dostoevskiy    3
unknown        1
Chekhov        1
Tolstoy        1
Pushkin        1
Name: author_name, dtype: int64

### построчное применение методов и функций в DataFrame

In [452]:
df7['book_title'].apply(lambda x: x.upper())

0                 UNKNOWN
1           WAR AND PEACE
2               THE IDIOT
3    CRIME AND PUNISHMENT
4        FATHERS AND SONS
5             THE GAMBLER
6           THREE SISTERS
Name: book_title, dtype: object

### группировка данных в DataFrame

1-й способ:

In [453]:
df7.groupby('author_name')['price'].max()

author_name
Chekhov        350.0
Dostoevskiy    500.0
Pushkin          NaN
Tolstoy        700.0
unknown          NaN
Name: price, dtype: float64

2-й способ

In [456]:
price_agg = df7.groupby('author_name').agg({'price': 'max'})
price_agg

price
author_name       
Chekhov      350.0
Dostoevskiy  500.0
Pushkin        NaN
Tolstoy      700.0
unknown        NaN

In [458]:
price_agg = price_agg.reset_index()
price_agg

index  author_name  price
0      0      Chekhov  350.0
1      1  Dostoevskiy  500.0
2      2      Pushkin    NaN
3      3      Tolstoy  700.0
4      4      unknown    NaN

In [459]:
price_agg = price_agg.drop('index', axis = 1)
price_agg

author_name  price
0      Chekhov  350.0
1  Dostoevskiy  500.0
2      Pushkin    NaN
3      Tolstoy  700.0
4      unknown    NaN

In [460]:
price_agg = price_agg.rename(columns={'price': 'max_price'})
price_agg

author_name  max_price
0      Chekhov      350.0
1  Dostoevskiy      500.0
2      Pushkin        NaN
3      Tolstoy      700.0
4      unknown        NaN